# Generated by Django 4.1.7 on 2023-03-19 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill_split', '0002_billusers_alter_billamounts_paid_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billusers',
            unique_together={('group', 'user')},
        ),
    ]
